apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo-app
spec:
  selector:
    matchLabels:
      app: k8s-demo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-demo-app
    spec:
      containers:
      - name: k8s-demo-app
        image: slavicviking/k8s-demo-app
        ports:
        - containerPort: 80